pipeline {
    agent any
    stages {
        stage('Clone repository') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: "*/main"]], userRemoteConfigs: [[url: 'https://github.com/NikhilHatake/PES2UG21CS336_Jenkins.git']]])
            }
        }
        stage('Build') {
            steps {
                dir('main') {
                    sh 'g++ -o output main/main.cpp'
                }
            }
        }
        stage('Test') {
            steps {
                sh './output'
            }
        }
        stage('Deploy') {
            steps {
                echo 'deploy'
            }
        }
    }
    post {
        failure {
            echo 'Pipeline failed'
        }
    }
}